# Generated by Django 4.1.5 on 2023-01-28 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_perfilusuario'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaDeCrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('P', 'Pânico'), ('D', 'Depressão'), ('A', 'Ansiedade')], default='A', max_length=1, null=True)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='contatoajuda',
            name='contato',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('E', 'Excelente')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='contatoajuda',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anotacao',
            name='tipo',
            field=models.CharField(choices=[('P', 'Positivo'), ('N', 'Negativo')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='contatoajuda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.perfilusuario'),
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
