# Generated by Django 4.1.5 on 2023-01-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alertadecrise_remove_avaliacao_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasDaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SE', 'Segunda'), ('TE', 'Terça'), ('QU', 'Quarta'), ('QI', 'Quinta'), ('SEX', 'Sexta'), ('SA', 'Sábado'), ('D', 'Domingo')], default='SE', max_length=3)),
            ],
        ),
    ]
