# Generated by Django 4.1.5 on 2023-01-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_active'),
        ('account', '0002_perfilusuario'),
    ]

    operations = [
    ]
